on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: Hosihikari.${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: Hosihikari.${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: artifact

      - run: |
          cp LICENSE.md artifact/

      - run: |
          zip -r ../hosihikari.preload.win-x64.zip *
        working-directory: artifact

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            hosihikari.preload.win-x64.zip
